version: "3.4"

services:
  web:
    image: nginx:1.15
    container_name: ${PROJECT_NAME}_web
    volumes:
     - ./docker/nginx/sites-enabled/site.conf:/etc/nginx/conf.d/site.conf
     - .:/app
    ports:
     - "8088:80"
    environment:
     - NGINX_HOST=site.loc
     - NGINX_PORT=80
    depends_on:
      - php
      - db
  php:
      build: docker/php
      container_name: ${PROJECT_NAME}_php
      volumes:
          - .:/app
          - ./docker/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    volumes:
      - ./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306

volumes:
    db_data: